server:
  port: 8888

spring:
  application:
    name: sm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tdhraik/configurations.git
          search-paths: services
